<?php

/**
 * Implements a helper function to capitalize words, handling delimiters.
 */
use Drupal\user\Entity\User;


function case_study_mail($key, &$message, $params) {

  $language = \Drupal::currentUser()->getPreferredLangcode();
  $language = $params['language'] ?? $language;
  $message['langcode'] = $language;

  switch ($key) {

case 'case_study_proposal_received':

  $proposal_id = $params['case_study_proposal_received']['proposal_id'];

  $proposal_data = \Drupal::database()
    ->select('case_study_proposal', 'csp')
    ->fields('csp')
    ->condition('id', $proposal_id)
    ->range(0, 1)
    ->execute()
    ->fetchObject();

  if (!$proposal_data) {
    return;
  }

  $user_data = \Drupal\user\Entity\User::load($params['case_study_proposal_received']['user_id']);

  $site_name = \Drupal::config('system.site')->get('name');

  $message['headers'] = $params['case_study_proposal_received']['headers'];
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8';

  $message['subject'] = t(
    '[@site] [Case Study Project] Your Case Study Project proposal has been received',
    ['@site' => $site_name]
  );

$message['body'][] = t(
'Dear @name,<br><br>

We have received your Case Study Project proposal with the following details:


  <b>Full Name:</b> @full_name<br>
  <b>Email:</b> @email<br>
  <b>University/Institute:</b> @university<br>
  <b>Department:</b> @department<br>
  <b>City:</b> @city<br>
  <b>State:</b> @state<br>
  <b>Country:</b> @country<br>
  <b>Project Title:</b> @project_title<br>
  <b>Description:</b> @description<br>
  <b>Date of Proposal:</b> @proposal_date<br>
  <b>Expected Date of Completion:</b> @completion_date


Your proposal is under review. You will soon receive an email when it is approved/disapproved.


Best Wishes,<br>
@site Team<br>
FOSSEE, IIT Bombay',
[
  '@name' => $proposal_data->contributor_name,
  '@full_name' => $proposal_data->name_title . ' ' . $proposal_data->contributor_name,
  '@email' => $user_data->getEmail(),
  '@university' => $proposal_data->university,
  '@department' => $proposal_data->department,
  '@city' => $proposal_data->city,
  '@state' => $proposal_data->state,
  '@country' => $proposal_data->country,
  '@project_title' => $proposal_data->project_title,
  '@description' => $proposal_data->description,
  '@proposal_date' => date('d/m/Y', $proposal_data->creation_date),
  '@completion_date' => date('d/m/Y', $proposal_data->expected_date_of_completion),
  '@site' => $site_name,
]);
break;

case 'case_study_proposal_approved':
  /* initializing data */
  $url = 'https://r.fossee.in/case-study-project/abstract-code';

  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['case_study_proposal_approved']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user_data = User::load($params['case_study_proposal_approved']['user_id']);

  $message['headers'] = $params['case_study_proposal_approved']['headers'];

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site][Case Study Project] Your Case Study Project proposal has been approved', [
    '@site' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['body'] = [
    'body' => t('
Dear ' . $proposal_data->contributor_name . ',

Your Case Study Project proposal with the following details has been approved:

Full Name: ' . $proposal_data->name_title . ' ' . $proposal_data->contributor_name . '
Email: ' . $user_data->getEmail() . '
University/Institute: ' . $proposal_data->university . '
Department: ' . $proposal_data->department . '
City: ' . $proposal_data->city . '
State: ' . $proposal_data->state . '
Country: ' . $proposal_data->country . '
Project Title: ' . $proposal_data->project_title . '
Description: ' . $proposal_data->description . '
Date of Proposal: ' . date('d/m/Y', $proposal_data->creation_date) . '
Expected Date of Completion: ' . date('d/m/Y', $proposal_data->expected_date_of_completion) . '


You can upload your project files at: ' . $url . '

Best Wishes,

@site Team,
FOSSEE, IIT Bombay', [
      '@site' => $site_name,
      '@user_name' => $user_data->getDisplayName(),
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;


case 'case_study_proposal_disapproved':
  /* initializing data */
  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['case_study_proposal_disapproved']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user_data = User::load($params['case_study_proposal_disapproved']['user_id']);
  //$user = user_load($params['case_study_proposal']['name']);

  $message['headers'] = $params['case_study_proposal_disapproved']['headers'];

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site][Case Study Project] Your Case Study Project proposal has been disapproved', [
    '@site' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['body'] = [
    'body' => t('
Dear ' . $proposal_data->contributor_name . ',

We regret to inform you that your Case Study proposal with following details have been disapproved:

Full Name: ' . $proposal_data->name_title . ' ' . $proposal_data->contributor_name . '
Email: ' . $user_data->getEmail() . '
University/Institute: ' . $proposal_data->university . '
Department: ' . $proposal_data->department . '
City: ' . $proposal_data->city . '
State: ' . $proposal_data->state . '
Country: ' . $proposal_data->country . '
Project Title: ' . $proposal_data->project_title . '
Description: ' . $proposal_data->description . '
Date of Proposal: ' . date('d/m/Y', $proposal_data->creation_date) . '
Expected Date of Completion: ' . date('d/m/Y', $proposal_data->expected_date_of_completion) . '

Reason for rejection: ' . $proposal_data->dissapproval_reason . '

You are welcome to submit a new proposal.

Best Wishes,

@site Team,
FOSSEE, IIT Bombay', [
      '@site' => $site_name,
      '@user_name' => $user_data->getDisplayName(),
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;

  case 'bulk_project_approved':

  $proposal = \Drupal::database()->select('case_study_proposal', 'csp')
    ->fields('csp')
    ->condition('id', $params['bulk_project_approved']['proposal_id'])
    ->execute()
    ->fetchObject();

  $user = \Drupal\user\Entity\User::load($params['bulk_project_approved']['user_id']);
  $site = \Drupal::config('system.site')->get('name');

  $message['headers'] = $params['bulk_project_approved']['headers'];

  $message['subject'] = t('[@site][Case Study] Your Case Study has been approved', ['@site' => $site]);

  $message['body'][] = t('
Dear @name,<br><br>

Congratulations! Your Case Study has been approved.<br><br>

<b>Project Title:</b> @title<br>
<b>Description:</b> @desc<br><br>

Best Wishes,<br>
@site Team',
  [
    '@name' => $proposal->contributor_name,
    '@title' => $proposal->project_title,
    '@desc' => $proposal->description,
    '@site' => $site,
  ]);

break;


case 'bulk_project_resubmit':

  $proposal = \Drupal::database()->select('case_study_proposal', 'csp')
    ->fields('csp')
    ->condition('id', $params['bulk_project_resubmit']['proposal_id'])
    ->execute()
    ->fetchObject();

  $site = \Drupal::config('system.site')->get('name');

  $message['headers'] = $params['bulk_project_resubmit']['headers'];

  $message['subject'] = t('[@site][Case Study] Resubmission Required', ['@site' => $site]);

  $message['body'][] = t('
Dear @name,<br><br>

Please resubmit your project:<br><br>

<b>Project Title:</b> @title<br>
<b>Reason:</b> @reason<br><br>

Best Wishes,<br>
@site Team',
  [
    '@name' => $proposal->contributor_name,
    '@title' => $proposal->project_title,
    '@reason' => $params['bulk_project_resubmit']['reason'],
    '@site' => $site,
  ]);

break;

case 'bulk_project_disapproved':

  $proposal = \Drupal::database()->select('case_study_proposal', 'csp')
    ->fields('csp')
    ->condition('id', $params['bulk_project_disapproved']['proposal_id'])
    ->execute()
    ->fetchObject();

  $site = \Drupal::config('system.site')->get('name');

  $message['headers'] = $params['bulk_project_disapproved']['headers'];

  $message['subject'] = t('[@site][Case Study] Your Case Study has been disapproved', ['@site' => $site]);

  $message['body'][] = t('
Dear @name,<br><br>

Your Case Study has been disapproved.<br><br>

<b>Project Title:</b> @title<br>
<b>Reason:</b> @reason<br><br>

Best Wishes,<br>
@site Team',
  [
    '@name' => $proposal->contributor_name,
    '@title' => $proposal->project_title,
    '@reason' => $params['bulk_project_disapproved']['reason'],
    '@site' => $site,
  ]);

break;


case 'case_study_proposal_completed':
  /* initializing data */
  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['case_study_proposal_completed']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user_data = User::load($params['case_study_proposal_completed']['user_id']);

  $message['headers'] = $params['case_study_proposal_completed']['headers'];

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site_name][Case Study Project] Your Case Study Project proposal has been completed', [
    '@site_name' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['body'] = [
    'body' => t('
Dear @name,

Your Case Study and abstract on the following process have been completed successfully.

Full Name: @full_name
Email: @email
University/Institute: @university
City: @city
State: @state
Country: @country
Project Title: @project_title

Best Wishes,

@site_name Team,
FOSSEE, IIT Bombay', [
      '@name' => $proposal_data->contributor_name,
      '@full_name' => $proposal_data->name_title . ' ' . $proposal_data->contributor_name,
      '@email' => $user_data->getEmail(),
      '@university' => $proposal_data->university,
      '@city' => $proposal_data->city,
      '@state' => $proposal_data->state,
      '@country' => $proposal_data->country,
      '@project_title' => $proposal_data->project_title,
      '@site_name' => $site_name,
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;


case 'case_study_proposal_deleted':
  /* initializing data */
  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['case_study_proposal_deleted']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user_data = User::load($params['case_study_proposal_deleted']['user_id']);

  $message['headers'] = $params['case_study_proposal_deleted']['headers'];

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site][Case Study Project] Your Case Study Project proposal has been deleted', [
    '@site' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['body'] = [
    'body' => t('
Dear ' . $proposal_data->contributor_name . ',

Your Case Study Project proposal with the following details has been deleted :

Full Name: ' . $proposal_data->name_title . ' ' . $proposal_data->contributor_name . '
Email: ' . $user_data->getEmail() . '
University/Institute: ' . $proposal_data->university . '
City: ' . $proposal_data->city . '
State: ' . $proposal_data->state . '
Country: ' . $proposal_data->country . '
Project Title: ' . $proposal_data->project_title . '

You can propose a new Case Study project.

Best Wishes,

@site Team,
FOSSEE, IIT Bombay', [
      '@site' => $site_name,
      '@user_name' => $user_data->getDisplayName(),
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;



case 'abstract_uploaded':
  // $solution_q = db_query("SELECT * FROM {case_study_solution} WHERE id = %d LIMIT 1", $params['abstract_uploaded']['solution_id']);

  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['abstract_uploaded']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user = User::load($params['abstract_uploaded']['user_id']);

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site][Case Study Project] You have uploaded Case Study project files', [
    '@site' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['headers'] = $params['abstract_uploaded']['headers'];

  $message['body'] = [
    'body' => t('
Dear ' . $proposal_data->contributor_name . ',

You have uploaded the Report and Code files for the following project:

Project Title: ' . $proposal_data->project_title . '


The report and code files are under review. You will be notified when it has been approved.

Best Wishes,

@site Team,
FOSSEE, IIT Bombay', [
      '@site' => $site_name,
      '@user_name' => $user->getDisplayName(),
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;

case 'abstract_edit_file_uploaded':
  // $solution_q = db_query("SELECT * FROM {case_study_solution} WHERE id = %d LIMIT 1", $params['abstract_uploaded']['solution_id']);

  $query = \Drupal::database()->select('case_study_proposal', 'csp');
  $query->fields('csp');
  $query->condition('id', $params['abstract_edit_file_uploaded']['proposal_id']);
  $query->range(0, 1);
  $proposal_data = $query->execute()->fetchObject();

  $user = User::load($params['abstract_edit_file_uploaded']['user_id']);
  $abs_file_name = $params['abstract_edit_file_uploaded']['abs_file'];
  $proj_file_name = $params['abstract_edit_file_uploaded']['proj_file'];

  $site_name = \Drupal::config('system.site')->get('name');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $message['subject'] = t('[@site][Case Study Project] You have updated code files/report of a case study', [
    '@site' => $site_name,
  ], [
    'langcode' => $langcode,
  ]);

  $message['headers'] = $params['abstract_edit_file_uploaded']['headers'];

  $message['body'] = [
    'body' => t('
Dear ' . $proposal_data->contributor_name . ',

You have updated the report/ code files for the following case study:

Project Title: ' . $proposal_data->project_title . '

Best Wishes,

@site Team,
FOSSEE, IIT Bombay', [
      '@site' => $site_name,
      '@user_name' => $user->getDisplayName(),
    ], [
      'langcode' => $langcode,
    ]),
  ];
  break;

  case 'standard':
  $message['subject'] = $params['standard']['subject'];
  $message['body'] = $params['standard']['body'];
  $message['headers'] = $params['standard']['headers'];
  break;
  }
}